### PR TITLE
Rewrote sort algorithm for the pipeline contributor graph...

### PR DESCRIPTION
**Pull request by dstockhammer**
Rewrote sort algorithm for the pipeline contributor graph to fix issues in some dependency combinations.

The API still allows creating circular dependency chains by having multiple notifications per contributor, as shown in unit test `registering_contributors_with_multiple_recursive_notifications_should_be_identified_as_invalid`.

A possible fix for this is to restrict the API in a way that it's only possible to register a single notification per contributor, but this would obviously be a breaking change. Having said that, not all contributors with multiple notifications cause the pipeline to break. As long as they're not referenced in any Before or After constraints, it should be fine.... it still seems a bit fragile though, since that's quite a lot of implicit knowledge and conditions.

### CODE REVIEW

**Comment by serialseb** [comment]
Are there any visible changes? That code is many many years old so I don't quite remember. There was a recursion defender once upon a time to prevent recursive pipelines no?
I wonder if it wouldn't be less risky for such things to adopt an append-only model for this, aka write a new class that does the new algorithm and leave the old one untouched, and switch to the new one, that allows swapping them around if it cases problems to people.

**Comment by dstockhammer** [comment]
Yes, the default (not sure about the correct term) order of items changes in some cases. All Before and After constraints are correctly satisfied though.

For example, if you have the items `A`, `B` and `C` and consider the rules `A before C` and `B after A`.
Both sequences are correct: `A -> B -> C`, `A -> C -> B`. 

In this example, the old algorithm could have produced the first sequence and the new one could produced the second one. Since both are logically correct, everything *should* still be fine. But some applications could rely on the order that is generated coincidentally because the algorithm happens to do it that way. In that case, those applications could break... But one could argue that it's not necessarily a bad thing to be forced to be more specific about the logical order ;)

But I see your point. I could implement this in a way that the old implementation is still used by default and you can opt-in to use the new one, if you think this is required.

The reason I made this change in the first place is that the old algorithm had issues in some cases with both Before and After constraints. Sometimes it would only satisfy one and the other one was ignored. I'm not quite sure why this happened, but my guess is that since both Before and After dependencies were maintained as separate lists, contributors being registered at a later point could overwrite/invalidate constraints of previous contributors.

**Comment by serialseb** [comment]
I'm happy with the new one being the new default if it works for you guys. I implemented the old one to privilege least-surprise to accuracy as it made people trip over when they were doing them. As it's a breaking change, if we make both available, whatever the default, and it can be easily changed, everyone is happy :)

**Comment by dstockhammer** [comment]
The old and new logic now exist side-by-side, with the old code being used by default. I moved the algorithm into a dedicated class, but left it almost unchanged. 

T switch o the new (or any other) algorithm, one has to register `IGenerateCallGraphs`, e.g.:
```cs
ResourceSpace.Uses.CustomDependency<IGenerateCallGraphs, TopologicalSortCallGraphGenerator>(DependencyLifetime.Singleton);
```

In order to allow the algorithms to live side-by-side, I created a new version of `DependencyNode`, called `DependencyNodeV2`. I admit that having V2 in the name is not ideal, but given the fact that it's internal, I thought it's acceptable and best suits the purpose.

Also, since the two algorithms don't necessarily generate the same order, I had to add version of `registering_all_the_contributors_results_in_a_correct_call_graph` for the new algorithm. Alternatively the test could be changed in a way that it only verifies the constraints, not the exact order. I can do that if you prefer it that way.

**Comment by serialseb** [comment]
If you guys are happy with that, im :+1:

**Comment by holytshirt** [comment]
Cool I'm happy too :+1:

**Pull request merged**
