### PR TITLE
Address DI issues in 2.6

### PR DESCRIPTION
**Pull request by gshackles**
Opening this now as a placeholder as we continue to dig into the issues in 2.6 that seem to be related to resolving enumerable types, and a place to put notes. The issues still persists even with these changes as well.

Some example stacktraces:

```
Message: Could not resolve an enumerable for ExceptionInterceptor

OpenRasta.DI.Internal.EnumerableProfile`1.TryResolve(IDependencyRegistrationCollection registrations, ResolveContext resolveContext, Object& instance):92
OpenRasta.DI.Internal.FuncProfile`1+<>c__DisplayClass3_0.<ResolveTyped>b__0()
OpenRasta.OperationModel.MethodBased.MethodBasedOperationCreator+<>c__DisplayClass9_0.<CreateSyncDescriptor>b__0():42
OpenRasta.OperationModel.MethodBased.OperationDescriptor.Create():1
OpenRasta.OperationModel.MethodBased.MethodBasedOperationCreator+<>c.<CreateOperations>b__6_0(OperationDescriptor o)
System.Linq.Enumerable+WhereSelectEnumerableIterator`2.MoveNext():77
System.Linq.Buffer`1..ctor(IEnumerable`1 source):114
System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source):20
OpenRasta.OperationModel.MethodBased.MethodBasedOperationCreator.CreateOperations(IEnumerable`1 handlers):73
OpenRasta.Pipeline.Contributors.OperationCreatorContributor.CreateOperations(ICommunicationContext context):40
OpenRasta.Pipeline.CallGraph.ContributorBuilder+<>c__DisplayClass17_0.<OpenRasta.Pipeline.IPipeline.Notify>b__0(ICommunicationContext ctx)
OpenRasta.Pipeline.RequestMiddleware+<Invoke>d__2.MoveNext():472
```

```
Message: Could not resolve type OpenRasta.OperationModel.IOperationExecutor

OpenRasta.DI.Internal.FuncProfile`1+<>c__DisplayClass3_0.<ResolveTyped>b__0():58
OpenRasta.Pipeline.Contributors.OperationInvokerContributor+<ExecuteOperations>d__3.MoveNext():15
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw():12
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task):40
System.Runtime.CompilerServices.TaskAwaiter`1.GetResult():11
OpenRasta.Pipeline.RequestMiddleware+<Invoke>d__2.MoveNext():568
```

### CODE REVIEW

**Comment by gshackles** [comment]
I'll also call out that I'm not 100% convinced the issue is actually with the container, and think the root issue might actually be the known problems with the ASP.NET host running under IIS...

**Comment by nmosafi** [comment]
> Scratch that, after doing some long-running tests it does seem like swapping the internal container out with Windsor does resolve this particular issue

What's the stacktrace when you have Windsor in place?

**Comment by gshackles** [comment]
> What's the stacktrace when you have Windsor in place?

There isn't one, was saying that switching to Windsor does seem to resolve the issue so far 😄

**Comment by nmosafi** [comment]
Ahh I misread. So definitely a bug in the internal container

**Comment by serialseb** [comment]
Internal container is dead code, so I'm closing this

**Pull request closed without merging**
