### PR TITLE
Improve content disposition header parsing.

### PR DESCRIPTION
**Pull request by tapmantwo**
Hi,

During uploads, we've noticed an issue where if any of the values in the Content-Disposition header contain semi colons, the upload fails with a 400 bad request.  Upon inspection it is because it can't find any content names, which is caused by the way the header is split by ';'.

I've updated to use a more robust regex, which ignores any quoted semi colons. Shamelessly stolen from here -> http://stackoverflow.com/questions/1757065/java-splitting-a-comma-separated-string-but-ignoring-commas-in-quotes

Cheers,

Richard

### CODE REVIEW

**Comment by holytshirt** [comment]
Looks OK to me. You probably also want to ad ```RegexOptions.Compiled```  to the regex

**Comment by holytshirt** [comment]
@serialseb what do you think?

**Comment by serialseb** [comment]
the 2.x branch of content disposition headers is faulty anyway and is rather complex to implement correctly. If that patch helps you, I'm :+1:

**Comment by holytshirt** [comment]
:+1:

**Pull request merged**
